import Link from "next/link";

type IconName = "spark" | "map" | "calendar" | "adjust" | "chart" | "arrow" | "play" | "check";

function Icon({ name, className = "" }: { name: IconName; className?: string }) {
  const paths: Record<IconName, React.ReactNode> = {
    spark: <><path d="M12 3l1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8L12 3Z" /><path d="M19 15l.8 2.2L22 18l-2.2.8L19 21l-.8-2.2L16 18l2.2-.8L19 15Z" /></>,
    map: <><path d="m4 6 5-2 6 2 5-2v14l-5 2-6-2-5 2V6Z" /><path d="M9 4v14M15 6v14" /></>,
    calendar: <><rect x="3" y="5" width="18" height="16" rx="2" /><path d="M16 3v4M8 3v4M3 10h18M8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01" /></>,
    adjust: <><path d="M4 7h16M4 17h16M8 7a2 2 0 1 0 0 .01M16 17a2 2 0 1 0 0 .01" /></>,
    chart: <><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" /></>,
    arrow: <><path d="M5 12h14M13 6l6 6-6 6" /></>,
    play: <path d="m9 7 8 5-8 5V7Z" fill="currentColor" stroke="none" />,
    check: <path d="m5 12 4 4L19 6" />,
  };
  return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

const planItems = [
  ["01", "Learn", "Prefix sums: the core idea", "28 min", "indigo"],
  ["02", "Practice", "Solve 4 focused problems", "35 min", "violet"],
  ["03", "Review", "Revisit yesterday's mistakes", "12 min", "amber"],
];
const subjects = ["Data Structures", "Programming", "System Design", "Interview Prep", "Web Development", "Data & AI"];

export default function Landing() {
  return <main className="landing overflow-hidden bg-[#fbfbfe] text-slate-950">
    <header className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8">
      <Link href="/" className="flex items-center gap-2.5" aria-label="Pathwise home"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-indigo-600 text-white"><Icon name="arrow" className="h-4 w-4 -rotate-45" /></span><span className="text-lg font-extrabold tracking-tight">pathwise<span className="text-indigo-600">.</span></span></Link>
      <nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 md:flex" aria-label="Main navigation"><a href="#how-it-works" className="transition hover:text-slate-950">How it works</a><a href="#subjects" className="transition hover:text-slate-950">Subjects</a><Link href="/login" className="transition hover:text-slate-950">Log in</Link></nav>
      <Link className="landing-button landing-button-small" href="/onboarding">Build my plan <Icon name="arrow" className="h-4 w-4" /></Link>
    </header>

    <section className="relative mx-auto grid max-w-7xl gap-14 px-5 pb-20 pt-14 sm:px-8 sm:pb-28 sm:pt-20 lg:grid-cols-[1.02fr_.98fr] lg:items-center lg:gap-10">
      <div className="relative z-10"><div className="landing-eyebrow"><span className="h-1.5 w-1.5 rounded-full bg-indigo-500" /> Your learning, with direction</div><h1 className="mt-6 max-w-3xl text-[3.15rem] font-extrabold leading-[.98] tracking-[-.06em] text-slate-950 sm:text-7xl lg:text-[5.25rem]">Stop searching.<br /><span className="text-indigo-600">Start learning.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600 sm:text-xl">Turn scattered playlists, courses and practice resources into a personalized learning plan that tells you exactly what to study next.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link className="landing-button" href="/onboarding">Build My Learning Plan <Icon name="arrow" className="h-4 w-4" /></Link><a className="landing-button-secondary" href="#how-it-works"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-slate-100"><Icon name="play" className="h-3.5 w-3.5" /></span> Explore Demo</a></div><div className="mt-8 flex items-center gap-3 text-sm text-slate-500"><div className="flex -space-x-2"><span className="avatar bg-amber-200">A</span><span className="avatar bg-pink-200">M</span><span className="avatar bg-sky-200">J</span></div><span>Built for learners who want momentum.</span></div></div>
      <div className="relative mx-auto w-full max-w-[560px] lg:mx-0 lg:justify-self-end"><div className="absolute -right-16 -top-12 h-56 w-56 rounded-full bg-violet-200/50 blur-3xl" /><div className="absolute -bottom-16 -left-14 h-52 w-52 rounded-full bg-sky-100 blur-3xl" /><div className="relative rounded-[28px] border border-slate-200/80 bg-white p-4 shadow-[0_28px_65px_-24px_rgba(60,72,130,.3)] sm:p-5"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-indigo-600">Tuesday, October 14</p><h2 className="mt-1 text-lg font-bold tracking-tight">Your learning plan</h2></div><span className="flex items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" /> On track</span></div><div className="mt-4 rounded-2xl bg-slate-950 p-4 text-white sm:p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-indigo-300">THIS WEEK</p><p className="mt-1 text-sm font-medium text-slate-300">You&apos;re building array confidence</p></div><div className="relative flex h-11 w-11 items-center justify-center rounded-full border-[4px] border-indigo-400 text-xs font-bold">60%</div></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/15"><div className="h-full w-3/5 rounded-full bg-indigo-400" /></div></div><div className="mt-3 space-y-2.5">{planItems.map(([number, type, item, duration]) => <div key={type} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3 transition hover:border-indigo-100 hover:bg-indigo-50/30"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-indigo-50 text-[10px] font-extrabold text-indigo-600">{number}</span><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{type}</p><p className="truncate text-sm font-semibold text-slate-800">{item}</p></div><span className="text-xs font-medium text-slate-400">{duration}</span></div>)}</div><div className="mt-4 flex items-center justify-between rounded-xl bg-indigo-50 px-3.5 py-3 text-sm"><span className="font-semibold text-indigo-950">Total focus time</span><span className="font-extrabold text-indigo-600">1h 15m</span></div></div><div className="absolute -bottom-6 -left-5 hidden rounded-2xl border border-slate-100 bg-white px-4 py-3 shadow-lg sm:flex sm:items-center sm:gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-amber-100 text-amber-700"><Icon name="spark" className="h-5 w-5" /></span><div><p className="text-xs font-bold">Next up, clearly.</p><p className="text-[11px] text-slate-500">No more wondering where to begin.</p></div></div></div>
    </section>

    <section className="border-y border-slate-200 bg-white/70"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><p className="section-label">The problem</p><h2 className="section-heading mt-4">Great resources are everywhere. <span className="text-slate-400">A clear next step isn&apos;t.</span></h2></div><p className="max-w-2xl text-lg leading-8 text-slate-600">Every search creates more tabs, more saved videos, and another decision. Planning quietly becomes the hardest part of learning.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{[["Too many tabs", "Courses, playlists, notes and problems all compete for your attention."], ["No clear order", "It&apos;s hard to know what foundation should come before the next topic."], ["Momentum stalls", "When you don&apos;t know what&apos;s next, it&apos;s easy to put learning off."]].map(([title, copy], index) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6"><span className="text-sm font-bold text-indigo-600">0{index + 1}</span><h3 className="mt-7 text-lg font-bold">{title}</h3><p className="mt-2.5 text-sm leading-6 text-slate-500">{copy}</p></article>)}</div></div></section>

    <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="max-w-2xl"><p className="section-label">How it works</p><h2 className="section-heading mt-4">Your plan starts with your real life.</h2><p className="mt-5 text-lg leading-8 text-slate-600">A little context is all it takes to turn a big goal into a useful next session.</p></div><div className="mt-14 grid gap-6 md:grid-cols-3">{[["01", "Share your goal", "Tell us what you want to learn, where you're starting, and how much time you have.", "spark"], ["02", "Get your roadmap", "We organize the right concepts, practice and resources into a sequence that makes sense.", "map"], ["03", "Follow today&apos;s plan", "Open one focused session each day and always know exactly what to do next.", "calendar"]].map(([number, title, copy, icon]) => <article key={number} className="relative rounded-2xl border border-slate-200 bg-white p-6 sm:p-7"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><Icon name={icon as IconName} className="h-5 w-5" /></span><span className="absolute right-7 top-8 text-sm font-extrabold text-slate-200">{number}</span><h3 className="mt-9 text-xl font-bold tracking-tight">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p></article>)}</div></section>

    <section className="bg-slate-950 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-2 lg:items-center"><div><p className="section-label text-indigo-300">Personalized roadmap</p><h2 className="section-heading mt-4 text-white">A sequence you can trust.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-300">Start in the right place, build the skills that unlock the next ones, and use the resources you already love in an order that works.</p><div className="mt-8 space-y-3">{["Built around your starting point", "Sized to your available time", "Connected to a meaningful goal"].map(item => <p key={item} className="flex items-center gap-3 text-sm font-medium text-slate-200"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-indigo-400 text-slate-950"><Icon name="check" className="h-3.5 w-3.5" /></span>{item}</p>)}</div></div><div className="rounded-3xl border border-white/10 bg-white/[.06] p-5 sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-300">Your roadmap</p><div className="mt-6 space-y-1">{[["1", "Foundations", "Arrays, complexity & iteration", true], ["2", "Core patterns", "Two pointers & sliding windows", false], ["3", "Problem solving", "Practice with feedback loops", false], ["4", "Interview ready", "Mixed sets & timed practice", false]].map(([number, title, copy, active]) => <div key={number as string} className={`flex gap-4 rounded-xl p-3.5 ${active ? "bg-indigo-400 text-slate-950" : "text-slate-300"}`}><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-xs font-bold ${active ? "bg-slate-950 text-white" : "bg-white/10"}`}>{number}</span><div><p className="text-sm font-bold">{title}</p><p className={`mt-0.5 text-xs ${active ? "text-slate-800" : "text-slate-500"}`}>{copy}</p></div></div>)}</div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="grid gap-14 lg:grid-cols-2 lg:items-center"><div className="order-2 lg:order-1"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Today&apos;s session</p><p className="mt-1 text-xl font-bold">Make progress in 75 min</p></div><span className="rounded-lg bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">Ready</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["Learn", "28 min", "Understand prefix sums"], ["Practice", "35 min", "Solve 4 problems"], ["Reflect", "12 min", "Capture key takeaways"]].map(([kind, time, copy], index) => <div key={kind} className="rounded-xl bg-slate-50 p-4"><span className="text-xs font-bold text-slate-400">0{index + 1} · {time}</span><p className="mt-5 font-bold">{kind}</p><p className="mt-1 text-xs leading-5 text-slate-500">{copy}</p></div>)}</div></div></div><div className="order-1 lg:order-2"><p className="section-label">Daily learning</p><h2 className="section-heading mt-4">One focused session. Every day.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">Your plan turns a large goal into a calm, practical session: learn something new, put it into practice, then keep what matters.</p><p className="mt-6 text-base font-semibold text-indigo-600">Open your plan. Know what&apos;s next. Begin. <Icon name="arrow" className="ml-1 inline h-4 w-4" /></p></div></div></section>

    <section className="border-y border-indigo-100 bg-indigo-50/60"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div><p className="section-label">Adaptive learning</p><h2 className="section-heading mt-4">A plan that responds to your progress.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">Some topics click fast. Others need another pass. Your roadmap adapts so your time goes where it can make the biggest difference.</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white p-6 shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-100 text-violet-700"><Icon name="adjust" className="h-5 w-5" /></span><h3 className="mt-7 font-bold">More help where needed</h3><p className="mt-2 text-sm leading-6 text-slate-500">Spend more time on tricky ideas and reinforce weak spots.</p></div><div className="rounded-2xl bg-indigo-600 p-6 text-white shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/15 text-white"><Icon name="spark" className="h-5 w-5" /></span><h3 className="mt-7 font-bold">Keep your pace</h3><p className="mt-2 text-sm leading-6 text-indigo-100">Move forward when you&apos;re ready, without getting held back.</p></div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="section-label">Progress tracking</p><h2 className="section-heading mt-4">Make your effort visible.</h2><p className="mt-5 max-w-md text-lg leading-8 text-slate-600">See what you&apos;ve covered, how your consistency is growing, and where to put your attention next.</p></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-6"><Icon name="chart" className="h-5 w-5 text-indigo-600" /><p className="mt-8 text-3xl font-extrabold tracking-tight">68%</p><p className="mt-1 text-sm text-slate-500">Roadmap complete</p></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><span className="text-xl">🔥</span><p className="mt-8 text-3xl font-extrabold tracking-tight">12 days</p><p className="mt-1 text-sm text-slate-500">Learning streak</p></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><span className="text-xl">◷</span><p className="mt-8 text-3xl font-extrabold tracking-tight">4.5h</p><p className="mt-1 text-sm text-slate-500">Focused this week</p></div></div></div></section>

    <section id="subjects" className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="section-label">Supported subjects</p><h2 className="section-heading mt-4">Start with what matters most.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">More learning paths are on the way. Pick a direction and make it yours.</p></div><div className="mt-11 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{subjects.map((subject, index) => <div key={subject} className="group flex items-center justify-between rounded-xl border border-slate-200 p-4 transition hover:border-indigo-200 hover:bg-indigo-50/40"><span className="font-semibold text-slate-800">{subject}</span><span className={`h-2 w-2 rounded-full ${index === 0 ? "bg-emerald-500" : "bg-slate-300"}`} title={index === 0 ? "Available now" : "Coming soon"} /></div>)}</div></div></section>

    <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl overflow-hidden rounded-[32px] bg-indigo-600 px-6 py-16 text-center text-white sm:px-12 sm:py-20"><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-200">Your next session is waiting</p><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-extrabold leading-tight tracking-[-.045em] sm:text-6xl">You don&apos;t have to figure out what to study next.</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-indigo-100">Build a learning plan that turns good intentions into a clear, everyday practice.</p><Link className="mt-9 inline-flex min-h-12 items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-indigo-700 shadow-sm transition hover:bg-indigo-50 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-indigo-600" href="/onboarding">Build My Learning Plan <Icon name="arrow" className="h-4 w-4" /></Link></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-4 px-5 pb-9 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-8"><Link href="/" className="font-extrabold tracking-tight text-slate-800">pathwise<span className="text-indigo-600">.</span></Link><p>Learn with direction.</p><div className="flex gap-5"><Link href="/login" className="hover:text-slate-800">Log in</Link><Link href="/onboarding" className="hover:text-slate-800">Get started</Link></div></footer>
  </main>;
}
