"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { topics } from "@/lib/data";
import { currentTopicId } from "@/lib/roadmap-engine";
import { recommendationFor } from "@/lib/recommendation-engine";
import { getState,saveState } from "@/lib/store";
import { PlannerState } from "@/lib/types";
export function Dashboard() { const [state,setState]=useState<PlannerState>({tasks:[],progress:[],resources:[]}); useEffect(()=>setState(getState()),[]); if(!state) return null; const today=state.tasks.filter(t=>!t.completed).slice(0,4); const current=currentTopicId(state.tasks); const topic=topics.find(t=>t.id===current); const done=state.tasks.filter(t=>t.completed).length; const percent=Math.round(done/state.tasks.length*100); const weak=state.progress.filter(p=>(p.assessmentScore??100)<80 || (p.practiceAccuracy??100)<80); function complete(id:string){const next={...state,tasks:state.tasks.map(t=>t.id===id?{...t,completed:true}:t)};saveState(next);setState(next);} return <div><p className="pill">YOUR PERSONAL PLAN</p><h1 className="mt-3 text-3xl font-bold">Good to see you. Here&apos;s your next step.</h1><div className="mt-7 grid gap-5 lg:grid-cols-3"><section className="card lg:col-span-2"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">Today&apos;s plan</h2><p className="mt-1 text-sm text-slate-600">{topic?.name} · {state.profile?.dailyMinutes} minutes available</p></div><Link href="/learn" className="btn-secondary text-sm">Open session</Link></div><div className="mt-5 space-y-2">{today.map((task,i)=><div key={task.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><button onClick={()=>complete(task.id)} aria-label={`Complete ${task.title}`} className="h-6 w-6 rounded-full border-2 border-indigo-500 text-xs text-indigo-700 hover:bg-indigo-50">{task.completed?"✓":i+1}</button><span className="flex-1 font-medium">{task.title}</span><span className="text-sm text-slate-500">{task.minutes} min</span></div>)}</div></section><aside className="card bg-indigo-700 text-white"><p className="text-sm font-semibold text-indigo-200">CURRENT TOPIC</p><h2 className="mt-2 text-2xl font-bold">{topic?.name}</h2><p className="mt-2 text-sm text-indigo-100">{topic?.description}</p><p className="mt-8 text-sm text-indigo-200">Deadline</p><p className="font-semibold">{state.profile?.deadline}</p></aside></div><div className="mt-5 grid gap-5 md:grid-cols-3"><div className="card"><p className="text-sm text-slate-500">Overall progress</p><p className="mt-2 text-3xl font-bold">{percent}%</p><div className="mt-3 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-indigo-600" style={{width:`${percent}%`}} /></div></div><div className="card"><p className="text-sm text-slate-500">Weekly consistency</p><p className="mt-2 text-3xl font-bold">1 <span className="text-base font-normal">day streak</span></p><p className="mt-3 text-sm text-slate-500">Complete today&apos;s session to keep it going.</p></div><div className="card"><p className="text-sm text-slate-500">Adaptive recommendation</p><p className="mt-2 font-semibold">{recommendationFor(weak[0])}</p></div></div></div>; }
